version: "3"

services:
  bot:
    container_name: bot
    restart: always
    build:
      context: ./bot
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
        APP_HOME: "/bot"
    depends_on:
      - postgres
    volumes:
      - ./bot:/bot
    environment:
      - DATABASE_URL=${POSTGRES_PROTOCOL}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - TOKEN=${TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_URL=${ADMIN_URL}

  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
    postgres_data: