version: "3.10"

services:
  bot: &bot
    restart: always
    container_name: telegram_bot
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        depend: ""
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TOKEN=${TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_URL=${ADMIN_URL}
      - DEBUG=True
    command: python ./src/actions.py
    volumes:
      - .:/app

  postgres:
    restart: always
    container_name: postgresql
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
    postgres_data: