version: "3"

services:
  bot:
    container_name: bot
    restart: always
    build:
      context: ./bot
      dockerfile: Dockerfile
      args:
        MODE: "--with dev"
        APP_HOME: "/bot"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TOKEN=${TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_URL=${ADMIN_URL}
    command: python -m app

  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
    postgres_data: