version: "3.10"

services:
  bot: &bot
    container_name: telegram_bot
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        depend: ""
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TOKEN=${TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_URL=${ADMIN_URL}
      - REDIS_URL=${REDIS_URL}
    command: python ./src/actions.py
    volumes:
      - .:/app

  redis:
    container_name: redis
    image: redis:7
    expose:
      - 6379

  postgres:
    container_name: postgresql
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  celery:
    <<: *bot
    container_name: celery
    command: celery -A src.celery_config.celery_app worker --beat --loglevel=debug
    ports: []

volumes:
    postgres_data: