version: "3.10"

services:

  bot: &bot
    restart: always
    container_name: telegram_bot
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        depend: --no-dev
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TOKEN=${TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_URL=${ADMIN_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBAPP_HOST=${WEBAPP_HOST}
      - WEBAPP_PORT=${WEBAPP_PORT}
      - WEBHOOK_SSL_CERT=${WEBHOOK_SSL_CERT}
      - WEBHOOK_SSL_PRIV=${WEBHOOK_SSL_PRIV}
      - DEBUG=False
    command: python ./src/actions.py
    expose:
      - 8000
    volumes:
      - .:/app

  redis:
    restart: always
    container_name: redis
    image: redis:7
    expose:
      - 6379

  postgres:
    restart: always
    container_name: postgresql
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  celery:
    <<: *bot
    restart: always
    container_name: celery
    command: celery -A src.celery_config.celery_app worker --beat --loglevel=debug
    ports: []

  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - bot
    ports:
      - 443:443

volumes:
    postgres_data: