version: "3.10"

services:

  bot: &bot
    restart: always
    container_name: telegram_bot
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        depend: --no-dev
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TOKEN=${TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_URL=${ADMIN_URL}
      - REDIS_URL=${REDIS_URL}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - WEBAPP_HOST=${WEBAPP_HOST}
      - WEBAPP_PORT=${WEBAPP_PORT}
      - DOMAIN=${DOMAIN}
      - DEBUG=False
    command: python ./src/actions.py
    expose:
      - 3001
    volumes:
      - .:/app

  redis:
    restart: always
    container_name: redis
    image: redis:7
    expose:
      - 6379

  postgres:
    restart: always
    container_name: postgresql
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  celery:
    <<: *bot
    restart: always
    container_name: celery
    command: celery -A src.celery_config.celery_app worker --beat --loglevel=info
    ports: []
  
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    depends_on:
      - bot
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${EMAIL} -d ${DOMAIN} --agree-tos

volumes:
    postgres_data: