version: "3"

services:
  bot:
    container_name: bot
    restart: always
    build:
      context: ./bot
      dockerfile: Dockerfile
      args:
        APP_HOME: "/bot"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TOKEN=${TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_URL=${ADMIN_URL}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - WEBAPP_HOST=${WEBAPP_HOST}
      - WEBAPP_PORT=${WEBAPP_PORT}
      - DOMAIN=${DOMAIN}
      - DEBUG=False
    expose:
      - 3001
    command: python -m app

  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./dumps:/dumps
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - bot
      - certbot
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/etc/letsencrypt --force-renewal --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}

  postgres-backup:
    image: rmiddle/pg_dump:latest
    container_name: postgres-backup
    restart: always
    links:
      - postgres
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDB=${POSTGRES_DB}
      - PGHOST=postgres
      - CRON_SCHEDULE=0 0 * * 0
      - DELETE_OLDER_THAN=1
    volumes:
      - ./dumps:/dump
    command: dump-cron

volumes:
  postgres_data:
