"""empty message

Revision ID: a33cac6e3ec5
Revises: 04b40d8736ce
Create Date: 2024-06-11 16:43:24.148873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a33cac6e3ec5'
down_revision = '04b40d8736ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('completed_practices', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('completed_practices', 'subject_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('groups', sa.Column('time_zone', sa.String(length=32), nullable=False))
    op.alter_column('groups', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('groups_id_seq'::regclass)"))
    op.alter_column('queue', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('queue', 'subject_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('schedule', sa.Column('week', sa.Enum('EACH_WEEK', 'EACH_ODD_WEEK', 'EACH_EVEN_WEEK', name='week'), nullable=False))
    op.alter_column('schedule', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('schedule', 'date_number',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='weekday'),
               nullable=False)
    op.drop_column('schedule', 'on_even_week')
    op.alter_column('subjects', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('subjects_id_seq'::regclass)"))
    op.alter_column('subjects', 'subject_type',
               existing_type=postgresql.ENUM('LABORATORY_WORK', 'COURSE_WORK', 'SUMMER_PRACTICE', 'GRADUATE_WORK', name='subject_type'),
               type_=sa.Enum('LABORATORY_WORK', 'COURSE_WORK', 'SUMMER_PRACTICE', 'GRADUATE_WORK', name='subjecttype'),
               existing_nullable=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('surname', sa.String(length=128), nullable=False))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'surname')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('subjects', 'subject_type',
               existing_type=sa.Enum('LABORATORY_WORK', 'COURSE_WORK', 'SUMMER_PRACTICE', 'GRADUATE_WORK', name='subjecttype'),
               type_=postgresql.ENUM('LABORATORY_WORK', 'COURSE_WORK', 'SUMMER_PRACTICE', 'GRADUATE_WORK', name='subject_type'),
               existing_nullable=False)
    op.alter_column('subjects', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('subjects_id_seq'::regclass)"))
    op.add_column('schedule', sa.Column('on_even_week', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('schedule', 'date_number',
               existing_type=sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='weekday'),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedule', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('schedule', 'week')
    op.alter_column('queue', 'subject_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('queue', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('groups', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('groups_id_seq'::regclass)"))
    op.drop_column('groups', 'time_zone')
    op.alter_column('completed_practices', 'subject_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('completed_practices', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
