"""empty message

Revision ID: d7e29d85ad9c
Revises: 265cd8cea7a9
Create Date: 2024-06-12 05:39:34.222065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e29d85ad9c'
down_revision = '265cd8cea7a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
