"""empty message

Revision ID: abef76b609e6
Revises: 2341881e5a6e
Create Date: 2024-07-02 15:59:29.460630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abef76b609e6'
down_revision = '2341881e5a6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'week',
               existing_type=postgresql.ENUM('EACH_WEEK', 'EACH_ODD_WEEK', 'EACH_EVEN_WEEK', name='week'),
               nullable=True)
    op.alter_column('schedule', 'date_number',
               existing_type=postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='weekday'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'week',
               existing_type=postgresql.ENUM('EACH_WEEK', 'EACH_ODD_WEEK', 'EACH_EVEN_WEEK', name='week'),
               nullable=False)
    op.alter_column('schedule', 'date_number',
               existing_type=postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='weekday'),
               nullable=False)
    # ### end Alembic commands ###
