"""First

Revision ID: fe21fdb55237
Revises: d07cecac8cd0
Create Date: 2022-08-13 17:56:08.825410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe21fdb55237'
down_revision = 'd07cecac8cd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
