from .create_edit_group import register_handlers_group  # noqa F401
from .create_subject import register_handlers_subject  # noqa F401
from .delete_account import register_handlers_delete_account  # noqa F401
from .delete_group import register_handlers_delete_group  # noqa F401
from .delete_subject import register_handlers_delete_subject  # noqa F401
from .edit_account import register_handlers_change_account  # noqa F401
from .select_group import register_handlers_select_group  # noqa F401
from .set_headman import register_handlers_set_headman  # noqa F401
from .stay_queue import register_handlers_stay_queue  # noqa F401
