"""queue_v2

Revision ID: c08dcfc66564
Revises: 7a7ff04119c7
Create Date: 2022-12-05 15:01:10.368202

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c08dcfc66564'
down_revision = '7a7ff04119c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('on_even_week', sa.Boolean(), nullable=True),
    sa.Column('date_number', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('can_select', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('days')
    op.drop_column('subjects', 'on_even_week')
    op.drop_column('subjects', 'can_select')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('can_select', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('subjects', sa.Column('on_even_week', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('days',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject'], ['subjects.id'], name='days_subject_fkey'),
    sa.PrimaryKeyConstraint('id', name='days_pkey')
    )
    op.drop_table('schedule')
    op.drop_table('completed_practices')
    # ### end Alembic commands ###
